name: .apk build for Reflex
on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@4.0.0
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@3.1.3

        with:
          path: app/build/outputs/apk/app-debug.apk