name: .apk build for Network sample
on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 3
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate apk
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/download-artifact@v2.1.1

        with:
          name: App Sample
          path: app/build/outputs/apk/app-debug.apk
