name: .apk build for Reflex
on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
          gradle-version: 6.5

    - name: Generate apk
      run: |
         cd /home/runner/work/NetworkSample/
         ./gradlew assembleRelease --stacktrace
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v1

      with:
          path: app/build/outputs/apk/app-debug.apk
