name: .apk build for Network sample
on:
  push:
    branches: [ "master","ci-cd" ]

  pull_request:
    branches: [ "master","ci-cd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Set up JDK 3
       uses: actions/setup-java@v3
       with:
          java-version: 17
          distribution: 'temurin'

     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2.11.0
       with:
          gradle-version: 6.5

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Generate apk
       run: ./gradlew build

     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v2.1.1
       with:
          name: Network Sample
          path: app/build/outputs/apk/debug/app-release.apk
